name = "stash"
main = "src/index.ts"

compatibility_date = "2024-07-25"

[ai]
binding = "AI"

[assets]
directory = "./src/frontend/dist"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "PASTE_STORAGE"
class_name = "PasteStorage"

[[vectorize]]
binding = "VECTORIZE"
index_name = "stash-embeddings"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PasteStorage"]

[observability]
enabled = true